### ISSUE TITLE
Corrected Variable Name for Spherical Harmonics Expansion Calculation

### ISSUE THREAD

**Issue by kaabir** [AllenCell/aics-shparam#12]
[aics-shparam
/docs/  ](https://github.com/AllenCell/aics-shparam/tree/main/docs)
	
_# Calculate the spherical harmonics expansion up to order lmax = 2
(coeffs, grid_rec), (image_, mesh, centroid, grid) = shparam.get_shcoeffs(image=img, lmax=2)_

There is a minor error in the line, it should be - _(coeffs, grid_rec), (image_, mesh, grid, transform) = shparam.get_shcoeffs(image=img, lmax=2)_

**Comment by vianamp** [comment]
Good catch! Thank you.

**Comment by vianamp** [comment]
Readme has been updated.
